### PR TITLE
style: layout changes

### PR DESCRIPTION
**Pull request by wgao19**
what does this PR do?
---
- addresses #2, make hero field more prominent
- adapt narrow screen

keyword "hero" field looks like this
---
image

narrow screen looks like this
---
image

### CODE REVIEW

**Comment by swyxio** [comment]
nice!

**Comment by fharper** [comment]
I love that style! Will it be merged?

**Comment by swyxio** [comment]
@fharper this was back when this was a react app and i decided to rewrite to svelte 😂  if you would like to do a design pass on the CURRENT version i'm more than happy to take some help!

**Comment by fharper** [comment]
OMG no, I'm the worst UI-wise 😂

**Pull request closed without merging**
